spring:
  application:
    name: CHECK-JWT
server:
  port: 1111
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1110/eureka